### PR TITLE
typescript to js compile

### PR DESCRIPTION
**Pull request by vflorusso**
added gulp task to compile typescript in js; added command to build.ps1 and build.sh

### Issue: #301 

 - [x ] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:
Briefly describe the work that has been done and how that differ from what was there before. Only a few sentences since reviewer should be able to find more information in the issue linked at the top.

### Test:
Describe how a reviewer should go ahead and test the introduced change(s) and/or what to look for.

(Make sure that all above information is provided before submitting your pull request)

### CODE REVIEW

**Comment by ankodu** [comment]
@vflorusso running the build.ps1 script I do get an error:

image

**Comment by vflorusso** [comment]
as I have added the gulp and typescript modules in the packages.json npm install should have done it when you first run again rundev.ps1. Build doesn't do the npm install part

**Comment by stuartleeks** [comment]
I've got a branch started to move the npm install etc to build - which I think is where it makes most sense.

Should I finish that up and send a PR?

**Comment by vflorusso** [comment]
@stuartleeks that should probably be in both as a dev might just want to run the rundev script or the rundev script should run the build script at some point to avoid duplication

**Pull request merged**
