### PR TITLE
Analytics Deployment

### PR DESCRIPTION
**Pull request by brentstineman**
### Issue: N/A

 - [ ] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:
Enhancements to bring the Event Hub into the "master" deployment. Includes integration with the environment settings for the web application. Also contains an initial and untested draft of the analytics template.  

### Test:
1) Run the deployment per the instructions on the in deployment/readme using the deploy.ps1 powershell script. 
2) Deploy the schema to the created "nether" database
3) Go to the https swagger endpoint and very you can successfully authorize using the swagger admin user and password
*if step 3 passes*  
4) run the integration tests against the deployed site 
5) Using service bus explorer or the Azure portal, ensure that messages have been sent to the event hub

Note: if using an existing resource group, remove the web site app service resource prior to running the deployment to ensure that all environment variables are "prestine". You can also skip step 2 if your nether database already has the base schema. 

(Make sure that all above information is provided before submitting your pull request)

### CODE REVIEW

**Comment by navalev** [comment]
Authorize in swagger ui resulted in unauthorized_client message.

Error is logs:
```
2017-02-16 13:40:17.718 +00:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize"
2017-02-16 13:40:17.813 +00:00 [Error] Invalid redirect_uri: http://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html
"{
  \"ClientId\": \"swaggerui\",
  \"ClientName\": \"SwaggerUI client\",
  \"RedirectUri\": \"http://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\",
  \"AllowedRedirectUris\": [
    \"https://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\"
  ],
  \"SubjectId\": \"anonymous\",
  \"RequestedScopes\": \"\",
  \"Raw\": {
    \"response_type\": \"token\",
    \"redirect_uri\": \"http://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\",
    \"realm\": \"swagger-ui-realm\",
    \"client_id\": \"swaggerui\",
    \"scope\": \"nether-all\",
    \"state\": \"oauth2\"
  }
}"
2017-02-16 13:40:17.827 +00:00 [Error] Request validation failed
2017-02-16 13:40:17.827 +00:00 [Information] "{
  \"ClientId\": \"swaggerui\",
  \"ClientName\": \"SwaggerUI client\",
  \"RedirectUri\": \"http://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\",
  \"AllowedRedirectUris\": [
    \"https://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\"
  ],
  \"SubjectId\": \"anonymous\",
  \"RequestedScopes\": \"\",
  \"Raw\": {
    \"response_type\": \"token\",
    \"redirect_uri\": \"http://ntst1602-website.azurewebsites.net/api/swagger/ui/o2c.html\",
    \"realm\": \"swagger-ui-realm\",
    \"client_id\": \"swaggerui\",
    \"scope\": \"nether-all\",
    \"state\": \"oauth2\"
  }
}"
2017-02-16 13:40:17.937 +00:00 [Information] Request finished in 281.5313ms 302 
```

**Comment by stuartleeks** [comment]
@navalev - can you try https://ntst1602-website.azurewebsites.net/api/swagger/ui/ ? (i.e. the HTTPS endpoint)?

**Comment by navalev** [comment]
Test passed with https://ntst1602-website.azurewebsites.net/api/swagger/ui/index.html

**Comment by brentstineman** [comment]
ok Nava, I think we're fully ready for a review now. Thanks!

**Pull request merged**
