### PR TITLE
updates to development setup documentation

### PR DESCRIPTION
**Pull request by brentstineman**
### Issue: none

 - [ ] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:
Expanded and edited the documentation related to developer's getting started. Corrected some spelling and grammatical errors while also filling in some gaps and generally trying to improve the flow of several markdown files. 

### Test:
All changes were for Markdown files. No running code was impacted.

### CODE REVIEW

**Comment by stuartleeks** [comment]
@brentstineman - when this is ready for reviewing and merging, can you add the `Review and Merge` label?

Actually, that's probably a step that should be added to the contributing docs :-)

**Comment by brentstineman** [comment]
@stuartleeks I can't seem to find the option to update the labels. :( Permission issue?

**Comment by ankodu** [comment]
@brentstineman Don't you have the "settings" symbols next to "Labels"?

**Comment by brentstineman** [comment]
nope

**Comment by ankodu** [comment]
@brentstineman I have just sent you an invite to join the Nether team. I assume it should work after you have accepted.

**Comment by brentstineman** [comment]
done and done. Thanks Anko :)

**Pull request merged**
