### PR TITLE
Analytics levels

### PR DESCRIPTION
**Pull request by oliviak**
### Issue: #315 #314 #237 #212 #145 

 - [ ] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:

- work in progress: documentation on the format of events to be sent from the client. To be found in documentation/api/analytics/events/
- work in progress: documentation on what outputs we can expect from the analytics building block. To be found in documentation/analytics/output/
- work in progress: documentation on what tables are being created using HDInsight and which query is doing it. To be found in documentation/analytics/analytics-deployment.md. Most likely to be integrated in the analytics.md document.
- 2 separate ARM templates to deploy 2 different ADF pipelines
- scripts focussing on level dropoff distribution, DAU, MAU, active sessions etc.
- PowerShell script to deploy the cold path of the analytics block. It assumes that one already has a storage account in which the game events are being collected. Finally, it deploys two ADFs using the before mentioned ARM templates. To be found in deployment/deployAnalyticsADF.ps1
- Introduced new events: LevelStart and LevelCompleted.

### Test:

Run deployment/deployAnalyticsADF.ps1

### CODE REVIEW

**Comment by ankodu** [comment]
@oliviak the deployment/deployAnalyticsADF.ps1 doesn't work for me. Why do I need to logon again for Azure? Can't you use the current credentials like the deploy.ps1 script. The script doesn't ask for any parameters but fails because it seems to expect input. Is there any documentation so I know what to do?

**Comment by oliviak** [comment]
- Put documentation on how to deploy
- configured the encoding of hive scripts to UTF-8
- changes to the ARM templates of ADF pipelines (fixed some errors)

**Comment by ankodu** [comment]
I get the following error running the deploy script. I tried this with a new RG and an existing RG.
image

**Comment by oliviak** [comment]
**Prerequisites for testing it:**
- Existing resource group
- Existing storage account which contains the raw game event data in a container called gameevents:
image

**Why an already existing storage account?**
At the moment, creating the event hubs and the corresponding blob storage for the ingest of game events is done either manually or by Brent's ARM templates. This ADF ARM template currently only takes care of the cold path (i.e. processing of the raw data that is already there, every 30 minutes for debugging purposes).

**To test it, do the following:**

1. Run deployment/deployAnalyticsADF.ps1. The parameters are as 
   - resourceGrp: Name of resource group that has already been created
   - location: Location of the resource group
   - scriptStorageAccount: Name of storage account to be created for uploading Hive scripts
   - storageAccount: Name of already existing storage account that contains the raw game event data
   - sqlServerName: Name of Azure SQL Server yet to be created
   - sqlServerAdminName: Login Username of Azure SQL Server
   - sqlServerAdminPassword: Password to the Azure SQL Server
   - dataFactoryName: Name of the data factory to be created

2. Run deployment/analytics-assets/CreateTables.sql to create required tables in the Azure SQL DB

**Left to do:**
- Integrate with Brent's ARM templates

**Pull request merged**
