### PR TITLE
First draft of Unity SDK for Nether

### PR DESCRIPTION
**Pull request by dgkanatsios**
### Issue: #385 

 - [ X] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:
Added a few methods to use Nether SDK from a Unity game

### CODE REVIEW

**Comment by krist00fer** [comment]
@dgkanatsios can you have a look if there is a seeting in Unity to save assets, unity and meta files as text/ascii instead of binaries. I got some hints that that can be done, but don't have a direct link to a solution. Just need to be sure what we accept.

**Comment by dgkanatsios** [comment]
@krist00fer latest commit should address that, everything is serialized to text now (both assets and settings). [Here](https://docs.unity3d.com/Manual/class-EditorManager.html) is the relevant entry in the Unity documentation.

**Comment by dgkanatsios** [comment]
Just bumped into Unity's recommendation of what should be checked in into source control systems, leaving it here for reference
https://docs.unity3d.com/Manual/ExternalVersionControlSystemSupport.html

**Comment by krist00fer** [comment]
All assets are now as text, that looks much better. I'll go ahead and review the content again.

**Pull request merged**
