### PR TITLE
Api Refactoring

### PR DESCRIPTION
**Pull request by stuartleeks**
### Issue: 

 - [x] Tick here to confirm that you have run RunCodeFormatter.ps1

### Description:
Refactoring APIs based on feedback from creating client

* Split Player Management controllers for easier navigation of methods. Enables applying authorization at the controler etc
* Tweak the API shape (e.g. /playerextended to /player/state)
* Split leader board and scores APIs
* Update integration tests
* update docs
* update load test

### Test:
Run Nether.Web and integration tests
Check you can log in to Swagger UI

### CODE REVIEW

**Comment by krist00fer** [comment]
Feels like we are dealing with quite a lot more than "just API Refactoring" but I'll keep reviewing

**Comment by stuartleeks** [comment]
It's refactoring the external API, and splitting out some of the large controllers to simplify them as I go :-)

**Comment by krist00fer** [comment]
I've looked at the changes from a helicopter perspective and it looks good. I think we should go ahead and merge.

**Comment by krist00fer2** [comment]
Reviewing last changes

**Pull request merged**
