### PR TITLE
Initial iOS SDK PR

### PR DESCRIPTION
**Pull request by juergenpf**
- [ ] Tick here to confirm that you have run RunCodeFormatter.ps1
N.A. as no manual code is involved yet (except Makefiles, bash scripts and config files)

### Description:
This first iOS SDK checkin provides the machinery on MacOS to enable the creation of an Objective-C CocoaPod and all the necessary scripts to actually create such a pod as repository "netherpod" in the current GitHub account. You may add the pod to your Xcode project, it should actually work.
Please note, that this first contains the automatic part of the API (generated from Swagger). The manual parts (Event-Hub messaging, Hartbeat etc.) will follow in the next days. You'll be busy first in setting up and make this drop work first, if it does you're prepared to get the additional parts.

### Test:
- Build Nether and run it locally
- Go to the iOS SDK source directory and run "make"
- Most likely you'll first encounter errors telling you which software you are missing on your Mac. Follow the instructions und re-run make until it builds successfully.

(Make sure that all above information is provided before submitting your pull request)

### CODE REVIEW

**Comment by krist00fer** [comment]
Thank you @juergenpf , I'll give it a try early next week.

**Comment by krist00fer** [comment]
```bash
*** You need to create a persnal access token in github and store it in environment varibale GIT_TOKEN.  Stop.
```

@juergenpf could you explain why I need to setup an access token in order to build the SDK? Am I missing something here?

**Comment by juergenpf** [comment]
Because in one of the build scripts the cocoapod is created/maintained on github, per default under the same github account as the current nether repository but that’s not necessarily always the case. So in order to be able to automatically update the cocoapod you must have the access token for that repo.

 

Jürgen

**Comment by juergenpf** [comment]
I take a look to relax that requirement when the cocoapod is hosted in the same github account (as is the Default currently) as nether itself.

Jürgen

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Kristofer Liljeblad<mailto:notifications@github.com>
Gesendet: Mittwoch, 31. Mai 2017 16:30
An: MicrosoftDX/nether<mailto:nether@noreply.github.com>
Cc: Jürgen Pfeifer<mailto:juergen@familiepfeifer.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [MicrosoftDX/nether] Initial iOS SDK PR (#526)


*** You need to create a persnal access token in github and store it in environment varibale GIT_TOKEN.  Stop.

@juergenpf<https://github.com/juergenpf> could you explain why I need to setup an access token in order to build the SDK? Am I missing something here?

**Comment by krist00fer** [comment]
Can we separate the compilation of the SDK from the publishing of the CocoaPod? Eventually we want to automate the builds on the build server without necessary publishing new CocoaPods? Can I help you with that?

**Comment by juergenpf** [comment]
You can already build without publishing, this are just separate targets in the Makefile.
If for dev/test purposes the cocoapod is published into the same account as the current nether repository it would make sense to omit the GIT_TOKEN requirement. Issue is, this is cocoapod tooling generated code and I dont want to break the toolchain with too much manual intervention because that would be error prone if the tooling changes. I'm working on it with lower prio (because you can already build without publishing), because at the moment I'm preparing the next PR with the manual code and the iOS test app.

**Comment by krist00fer** [comment]
Closing this PR for now, since no work is being done at the moment to adress the issues that need to be fixed in order to be incorporated into the main branch. We'll open it again as soon as we see progress.

**Pull request closed without merging**
